import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { gunzipSync } from "node:zlib";
import { describe, expect, test } from "./_expect.ts";
import { emitSoraneAstroArtifacts, soraneAstro } from "../packages/astro/src/index.ts";

function fixtureRoot(): string {
  const root = mkdtempSync(join(tmpdir(), "sorane-astro-"));
  const posts = join(root, "src", "content", "posts");
  mkdirSync(posts, { recursive: true });
  writeFileSync(
    join(posts, "hello.md"),
    `---
type: article
title: Hello Astro
description: OKF on Astro
timestamp: 2026-06-25T00:00:00Z
profile: sorane-okf/0.2
digitalSourceType: trainedAlgorithmicMedia
---

# Hello
`,
  );
  return root;
}

describe("@sorane/astro", () => {
  test("emits OKF artifacts from Astro content", async () => {
    const root = fixtureRoot();
    const result = await emitSoraneAstroArtifacts({
      root,
      site: {
        title: "Astro Site",
        description: "Astro with sorane",
        baseUrl: "https://example.dev",
      },
      collections: { posts: "blog" },
    });

    expect(result.concepts).toBe(1);
    expect(result.files).toContain("catalog.jsonld");
    expect(result.files).toContain("llms.txt");
    expect(result.files).toContain("okf/bundle.tar.gz");

    const catalog = readFileSync(join(root, "dist", "catalog.jsonld"), "utf8");
    expect(catalog).toContain("Hello Astro");
    expect(catalog).toContain("https://example.dev/blog/hello.html");

    const llms = readFileSync(join(root, "dist", "llms.txt"), "utf8");
    expect(llms).toContain("Generated by `@sorane/astro`");
    expect(llms).toContain("Native backends");
    expect(llms).toContain("Labeled articles: 1");

    const tar = gunzipSync(readFileSync(join(root, "dist", "okf", "bundle.tar.gz")));
    expect(tar.toString("utf8")).toContain("article/posts-hello.md");
  });

  test("Astro integration hook delegates to emitter", async () => {
    const root = fixtureRoot();
    const integration = soraneAstro({
      root,
      site: { title: "S", description: "D" },
      outputs: { catalog: false, okfBundle: false, llmsTxt: true },
    });

    await integration.hooks["astro:build:done"]({
      dir: new URL(`file://${join(root, "public-dist")}/`),
    });

    expect(existsSync(join(root, "public-dist", "llms.txt"))).toBe(true);
    expect(existsSync(join(root, "public-dist", "catalog.jsonld"))).toBe(false);
  });
});
