import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { gunzipSync } from "node:zlib";
import { describe, expect, test } from "./_expect.ts";
import { emitSoraneAstroArtifacts, soraneAstro } from "../packages/astro/src/index.ts";

function fixtureRoot(): string {
  const root = mkdtempSync(join(tmpdir(), "sorane-astro-"));
  const posts = join(root, "src", "content", "posts");
  mkdirSync(posts, { recursive: true });
  writeFileSync(
    join(posts, "hello.md"),
    `---
type: article
title: Hello Astro
description: OKF on Astro
timestamp: 2026-06-25T00:00:00Z
profile: sorane-okf/0.2
digitalSourceType: trainedAlgorithmicMedia
---

# Hello
`,
  );
  return root;
}

describe("@sorane/astro", () => {
  test("emits OKF artifacts from Astro content", async () => {
    const root = fixtureRoot();
    const result = await emitSoraneAstroArtifacts({
      root,
      site: {
        title: "Astro Site",
        description: "Astro with sorane",
        baseUrl: "https://example.dev",
      },
      collections: { posts: "blog" },
    });

    expect(result.concepts).toBe(1);
    expect(result.validationErrors).toBe(0);
    expect(result.files).toContain("catalog.jsonld");
    expect(result.files).toContain("llms.txt");
    expect(result.files).toContain("okf/bundle.tar.gz");

    const catalog = readFileSync(join(root, "dist", "catalog.jsonld"), "utf8");
    expect(catalog).toContain("Hello Astro");
    expect(catalog).toContain("https://example.dev/blog/hello.html");

    const llms = readFileSync(join(root, "dist", "llms.txt"), "utf8");
    expect(llms).toContain("Generated by `@sorane/astro`");
    expect(llms).toContain("Native backends");
    expect(llms).toContain("Labeled articles: 1");

    const tar = gunzipSync(readFileSync(join(root, "dist", "okf", "bundle.tar.gz")));
    expect(tar.toString("utf8")).toContain("article/posts-hello.md");
  });

  test("Astro integration hook delegates to emitter", async () => {
    const root = fixtureRoot();
    const integration = soraneAstro({
      root,
      site: { title: "S", description: "D" },
      outputs: { catalog: false, okfBundle: false, llmsTxt: true },
    });

    await integration.hooks["astro:build:done"]({
      dir: new URL(`file://${join(root, "public-dist")}/`),
    });

    expect(existsSync(join(root, "public-dist", "llms.txt"))).toBe(true);
    expect(existsSync(join(root, "public-dist", "catalog.jsonld"))).toBe(false);
  });

  test("validate error mode fails on invalid OKF content", async () => {
    const root = mkdtempSync(join(tmpdir(), "sorane-astro-invalid-"));
    const posts = join(root, "src", "content", "posts");
    mkdirSync(posts, { recursive: true });
    writeFileSync(
      join(posts, "bad.md"),
      `---
title: Missing type
---

body
`,
    );

    let threw = false;
    try {
      await emitSoraneAstroArtifacts({
        root,
        site: { title: "S", description: "D" },
        validate: "error",
      });
    } catch (e) {
      threw = e instanceof Error && e.message.includes("content validation");
    }

    expect(threw).toBe(true);
  });

  test("permalink:directory produces index.html paths", async () => {
    const root = mkdtempSync(join(tmpdir(), "sorane-astro-dir-"));
    const posts = join(root, "src", "content", "posts");
    mkdirSync(posts, { recursive: true });
    writeFileSync(
      join(posts, "my-post.md"),
      `---
type: article
title: Dir Post
description: permalink test
timestamp: 2026-07-04T00:00:00Z
---
body
`,
    );

    const result = await emitSoraneAstroArtifacts({
      root,
      site: { title: "S", description: "D", baseUrl: "https://example.dev" },
      permalink: "directory",
      collections: { posts: "blog" },
      outputs: { catalog: true, llmsTxt: false, okfBundle: false },
    });

    expect(result.concepts).toBe(1);
    const catalog = readFileSync(join(root, "dist", "catalog.jsonld"), "utf8");
    expect(catalog).toContain("https://example.dev/blog/my-post/index.html");
  });

  test("index.md at collection root maps to index.html", async () => {
    const root = mkdtempSync(join(tmpdir(), "sorane-astro-idx-"));
    const docs = join(root, "src", "content", "docs");
    mkdirSync(docs, { recursive: true });
    writeFileSync(
      join(docs, "index.md"),
      `---
type: index
title: Docs Index
description: index page
timestamp: 2026-07-04T00:00:00Z
---
body
`,
    );
    writeFileSync(
      join(docs, "guide.md"),
      `---
type: article
title: Guide
description: guide
timestamp: 2026-07-04T00:00:00Z
---
body
`,
    );

    const result = await emitSoraneAstroArtifacts({
      root,
      site: { title: "S", description: "D", baseUrl: "https://example.dev" },
      collections: { docs: "docs" },
      outputs: { catalog: true, sitemap: true, llmsTxt: false, okfBundle: false },
    });

    expect(result.concepts).toBe(2);
    const catalog = readFileSync(join(root, "dist", "catalog.jsonld"), "utf8");
    // index type は catalog.hasPart から除外される（sorane 本体と同じ）
    expect(catalog).toContain("https://example.dev/docs/guide.html");
    const sitemap = readFileSync(join(root, "dist", "sitemap.xml"), "utf8");
    expect(sitemap).toContain("https://example.dev/docs/index.html");
  });

  test("nested subdirectory preserves path segments", async () => {
    const root = mkdtempSync(join(tmpdir(), "sorane-astro-nest-"));
    const nested = join(root, "src", "content", "docs", "api", "v2");
    mkdirSync(nested, { recursive: true });
    writeFileSync(
      join(nested, "endpoints.md"),
      `---
type: reference
title: API v2 Endpoints
description: reference
timestamp: 2026-07-04T00:00:00Z
---
body
`,
    );

    const result = await emitSoraneAstroArtifacts({
      root,
      site: { title: "S", description: "D", baseUrl: "https://example.dev" },
      outputs: { catalog: true, llmsTxt: false, okfBundle: false },
    });

    expect(result.concepts).toBe(1);
    const catalog = readFileSync(join(root, "dist", "catalog.jsonld"), "utf8");
    expect(catalog).toContain("https://example.dev/docs/api/v2/endpoints.html");
  });

  test("collection mapped to root (empty string) strips prefix", async () => {
    const root = mkdtempSync(join(tmpdir(), "sorane-astro-rootmap-"));
    const pages = join(root, "src", "content", "pages");
    mkdirSync(pages, { recursive: true });
    writeFileSync(
      join(pages, "about.md"),
      `---
type: article
title: About
description: about page
timestamp: 2026-07-04T00:00:00Z
---
body
`,
    );

    const result = await emitSoraneAstroArtifacts({
      root,
      site: { title: "S", description: "D", baseUrl: "https://example.dev" },
      collections: { pages: "" },
      outputs: { catalog: true, llmsTxt: false, okfBundle: false },
    });

    expect(result.concepts).toBe(1);
    const catalog = readFileSync(join(root, "dist", "catalog.jsonld"), "utf8");
    expect(catalog).toContain("https://example.dev/about.html");
  });

  test("sitemap output is off by default and toggleable", async () => {
    const root = fixtureRoot();

    // Default: sitemap off
    await emitSoraneAstroArtifacts({
      root,
      site: { title: "S", description: "D" },
    });
    expect(existsSync(join(root, "dist", "sitemap.xml"))).toBe(false);

    // Explicitly enabled
    const result = await emitSoraneAstroArtifacts({
      root,
      outDir: join(root, "dist2"),
      site: { title: "S", description: "D", baseUrl: "https://example.dev" },
      outputs: { sitemap: true, catalog: false, llmsTxt: false, okfBundle: false },
    });
    expect(result.files).toContain("sitemap.xml");
    expect(existsSync(join(root, "dist2", "sitemap.xml"))).toBe(true);
  });

  test("missing content directory returns empty result without throwing", async () => {
    const root = mkdtempSync(join(tmpdir(), "sorane-astro-empty-"));
    const warnings: string[] = [];
    const result = await emitSoraneAstroArtifacts({
      root,
      site: { title: "S", description: "D" },
      logger: { warn: (m) => warnings.push(m) },
    });

    expect(result.concepts).toBe(0);
    expect(result.files.length).toBe(0);
    expect(warnings.some((w) => w.includes("content directory not found"))).toBe(true);
  });

  test("validate:warn collects warnings but does not throw", async () => {
    const root = mkdtempSync(join(tmpdir(), "sorane-astro-warn-"));
    const posts = join(root, "src", "content", "posts");
    mkdirSync(posts, { recursive: true });
    writeFileSync(
      join(posts, "no-type.md"),
      `---
title: No Type Here
---
body
`,
    );

    const warnings: string[] = [];
    let threw = false;
    try {
      await emitSoraneAstroArtifacts({
        root,
        site: { title: "S", description: "D" },
        validate: "warn",
        logger: { warn: (m) => warnings.push(m) },
      });
    } catch {
      threw = true;
    }

    expect(threw).toBe(false);
    expect(warnings.some((w) => w.includes("content validation"))).toBe(true);
  });

  test("integration-layer validation applies with native backend", async (t) => {
    const { soraneAstroNativeCliAvailable } = await import(
      "../packages/astro/src/backend-cli.ts"
    );
    if (!soraneAstroNativeCliAvailable()) {
      t.skip("sorane-astro-backend native binary not built");
      return;
    }

    const root = mkdtempSync(join(tmpdir(), "sorane-astro-native-val-"));
    const posts = join(root, "src", "content", "posts");
    mkdirSync(posts, { recursive: true });
    writeFileSync(
      join(posts, "img.md"),
      `---
type: article
title: Image Alt
timestamp: 2026-07-04T00:00:00Z
---

![](assets/photo.png)
`,
    );

    const warnings: string[] = [];
    await emitSoraneAstroArtifacts({
      root,
      site: { title: "S", description: "D" },
      backend: "auto",
      validate: "warn",
      logger: { warn: (m) => warnings.push(m) },
    });

    expect(warnings.some((w) => w.includes("image missing alt text"))).toBe(true);
  });

  test("validate:false skips integration validation", async () => {
    const root = mkdtempSync(join(tmpdir(), "sorane-astro-no-val-"));
    const posts = join(root, "src", "content", "posts");
    mkdirSync(posts, { recursive: true });
    writeFileSync(
      join(posts, "img.md"),
      `---
type: article
title: No Validate
timestamp: 2026-07-04T00:00:00Z
---

![](assets/photo.png)
`,
    );

    const result = await emitSoraneAstroArtifacts({
      root,
      site: { title: "S", description: "D" },
      validate: false,
    });

    expect(result.validationErrors).toBe(0);
    expect(result.validationWarnings).toBe(0);
  });

  test("integration validation is not duplicated by native backend", async (t) => {
    const { runSoraneAstroCliBackend, soraneAstroNativeCliAvailable } = await import(
      "../packages/astro/src/backend-cli.ts"
    );
    const { buildSoraneAstroBackendInput, collectSoraneAstroBackendFiles } = await import(
      "../packages/astro/src/index.ts"
    );
    if (!soraneAstroNativeCliAvailable()) {
      t.skip("sorane-astro-backend native binary not built");
      return;
    }

    const root = mkdtempSync(join(tmpdir(), "sorane-astro-val-dedup-"));
    const posts = join(root, "src", "content", "posts");
    mkdirSync(posts, { recursive: true });
    writeFileSync(
      join(posts, "img.md"),
      `---
type: article
title: Dedup
timestamp: 2026-07-04T00:00:00Z
---

![](assets/photo.png)
`,
    );

    const files = collectSoraneAstroBackendFiles(join(root, "src", "content"));
    const input = buildSoraneAstroBackendInput(
      { site: { title: "S", description: "D" }, validate: "warn" },
      { root, contentDir: join(root, "src", "content"), outDir: join(root, "dist") },
      files,
    );

    const standalone = runSoraneAstroCliBackend(input);
    expect(standalone.validationWarnings).toBe(1);

    const integrated = await emitSoraneAstroArtifacts({
      root,
      site: { title: "S", description: "D" },
      backend: "cli",
      validate: "warn",
    });
    expect(integrated.validationWarnings).toBe(1);
  });

  test("backend auto prefers native CLI when built", async () => {
    const root = fixtureRoot();
    const warnings: string[] = [];
    const result = await emitSoraneAstroArtifacts({
      root,
      site: { title: "S", description: "D" },
      backend: "auto",
      validate: false,
      logger: { warn: (m) => warnings.push(m) },
    });
    expect(result.concepts).toBe(1);
    expect(warnings.some((w) => w.includes("not available yet"))).toBe(false);
  });

  test("backend wasm emits artifacts via @sorane/astro-backend-wasm", async () => {
    const root = fixtureRoot();
    const warnings: string[] = [];
    const result = await emitSoraneAstroArtifacts({
      root,
      outDir: join(root, "dist-wasm"),
      site: { title: "S", description: "D" },
      backend: "wasm",
      validate: false,
      logger: { warn: (m) => warnings.push(m) },
    });
    expect(result.concepts).toBe(1);
    expect(result.files).toContain("catalog.jsonld");
    expect(warnings.some((w) => w.includes("astro-backend-wasm is unavailable"))).toBe(false);
  });

  test("search output is off by default and emits assets when enabled", async () => {
    const root = mkdtempSync(join(tmpdir(), "sorane-astro-search-"));
    const posts = join(root, "src", "content", "posts");
    mkdirSync(posts, { recursive: true });
    writeFileSync(
      join(posts, "searchable.md"),
      `---
type: article
title: Searchable Post
description: search output test
timestamp: 2026-07-04T00:00:00Z
---

# Searchable

This article has enough body text to produce at least one search chunk when
@sorane/astro indexes Astro content during the integration hook.
`,
    );

    await emitSoraneAstroArtifacts({
      root,
      site: { title: "S", description: "D" },
      outputs: { catalog: false, llmsTxt: false, okfBundle: false, sitemap: false },
    });
    expect(existsSync(join(root, "dist", "assets", "search-index.json"))).toBe(false);

    const result = await emitSoraneAstroArtifacts({
      root,
      outDir: join(root, "dist-search"),
      site: { title: "S", description: "D", baseUrl: "https://example.dev" },
      collections: { posts: "blog" },
      outputs: {
        catalog: false,
        llmsTxt: false,
        okfBundle: false,
        sitemap: false,
        search: true,
      },
      search: { force: true },
    });

    expect(result.files).toContain("assets/search-index.json");
    expect(existsSync(join(root, "dist-search", "assets", "search-index.json"))).toBe(true);
    const index = readFileSync(join(root, "dist-search", "assets", "search-index.json"), "utf8");
    expect(index).toContain("blog/searchable.html");
  });

  test("search-backend prefers native index when CLI is built", async (t) => {
    const { soraneAstroNativeCliAvailable } = await import(
      "../packages/astro/src/backend-cli.ts"
    );
    const { buildSearchArtifacts } = await import("../packages/astro/src/search-backend.ts");
    const { SORANE_ASTRO_BACKEND_SCHEMA_VERSION } = await import(
      "../packages/astro/src/contract.ts"
    );
    if (!soraneAstroNativeCliAvailable()) {
      t.skip("sorane-astro-backend native binary not built");
      return;
    }

    const root = mkdtempSync(join(tmpdir(), "sorane-astro-native-search-"));
    const contentDir = join(root, "src", "content", "posts");
    mkdirSync(contentDir, { recursive: true });
    const source = `---
type: article
title: Native Search Index
timestamp: 2026-07-04T00:00:00Z
---

Enough body text for native search index path via Astro search-backend fallback.
`;
    writeFileSync(join(contentDir, "native-index.md"), source, "utf8");

    const infos: string[] = [];
    const artifacts = await buildSearchArtifacts(
      {
        schema_version: SORANE_ASTRO_BACKEND_SCHEMA_VERSION,
        root,
        contentDir: join(root, "src", "content"),
        outDir: join(root, "dist"),
        site: { title: "S", description: "D", baseUrl: "https://example.dev" },
        files: [{ relPath: "posts/native-index.md", source }],
        collections: { posts: "blog" },
        outputs: { search: true },
        search: { force: true },
      },
      { info: (m) => infos.push(m) },
    );

    expect(artifacts.some((a) => a.path === "assets/search-index.json")).toBe(true);
    expect(infos.some((m) => m.includes("(native)"))).toBe(true);
  });

  test("dcat catalog output when openData.dcatCatalog is enabled", async () => {
    const root = mkdtempSync(join(tmpdir(), "sorane-astro-dcat-"));
    const data = join(root, "src", "content", "data");
    mkdirSync(data, { recursive: true });
    writeFileSync(
      join(data, "stats.md"),
      `---
type: dataset
title: Open Stats
description: sample dataset
timestamp: 2026-07-04T00:00:00Z
identifier: stats-001
distribution:
  - title: CSV
    format: text/csv
    accessURL: stats.csv
---
body
`,
    );

    const result = await emitSoraneAstroArtifacts({
      root,
      site: { title: "S", description: "D", baseUrl: "https://example.dev" },
      openData: { dcatCatalog: true, defaultLicense: "CC-BY-4.0" },
      outputs: { catalog: true, llmsTxt: false, okfBundle: false, sitemap: false },
      validate: false,
    });

    expect(result.files).toContain("catalog-dcat.jsonld");
    const dcat = readFileSync(join(root, "dist", "catalog-dcat.jsonld"), "utf8");
    expect(dcat).toContain("dcat:Dataset");
    expect(dcat).toContain("Open Stats");
  });

  test("mdx quality gate uses validateSiteContent parity", async () => {
    const root = mkdtempSync(join(tmpdir(), "sorane-astro-mdx-"));
    const posts = join(root, "src", "content", "posts");
    mkdirSync(posts, { recursive: true });
    writeFileSync(
      join(posts, "bad-heading.mdx"),
      `---
type: article
title: MDX Bad Heading
description: mdx gate
timestamp: 2026-07-04T00:00:00Z
---

### skipped level
`,
    );

    let threw = false;
    try {
      await emitSoraneAstroArtifacts({
        root,
        site: { title: "S", description: "D" },
        validate: "error",
        quality: { heading: "error" },
      });
    } catch (e) {
      threw = e instanceof Error && e.message.includes("content validation");
    }
    expect(threw).toBe(true);
  });

  test("quality gate parity via validateSiteContent", async () => {
    const root = mkdtempSync(join(tmpdir(), "sorane-astro-quality-"));
    const posts = join(root, "src", "content", "posts");
    mkdirSync(posts, { recursive: true });
    writeFileSync(
      join(posts, "bad-heading.md"),
      `---
type: article
title: Bad Heading
description: heading gate
timestamp: 2026-07-04T00:00:00Z
---

### skipped level
`,
    );

    let threw = false;
    try {
      await emitSoraneAstroArtifacts({
        root,
        site: { title: "S", description: "D" },
        validate: "error",
        quality: { heading: "error" },
      });
    } catch (e) {
      threw = e instanceof Error && e.message.includes("content validation");
    }
    expect(threw).toBe(true);
  });
});
