/** Shared llms.txt sections for Astro integration backends. */
export const ASTRO_LLMS_EXTRA_SECTIONS: readonly string[] = [
  "## Astro integration\n\nGenerated by `@sorane/astro`. Astro owns page rendering; sorane owns OKF and agent-readable publishing artifacts.",
  "## Native backends\n\nThe integration boundary is intentionally file-based so OKF parsing, validation, bundle creation, and search indexing can move to Rust/WASM or a Rust CLI without changing Astro routes.",
];