import { escape, formCsrf } from '../vendor/mikaki/oidc.ts';
import { can, ROLES, type Site, type Proposal, type Role } from './store.ts';
import { icon, roleLabels } from './ui.ts';

const date=(seconds:number)=>new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(seconds*1000));
export function validationFeedback(value:string|null):string {
  if(!value) return '';
  try {
    const report=JSON.parse(value) as {files:{file:string;findings:{severity:string;message:string}[]}[]};
    const findings=report.files.flatMap(file=>file.findings.map(finding=>({file:file.file,...finding}))).slice(0,20);
    return findings.length?`<details class="validation"><summary>原稿のチェック結果を確認</summary><ul>${findings.map(finding=>`<li>${escape(finding.file)}：${escape(finding.message)}</li>`).join('')}</ul></details>`:'';
  }catch{return '';}
}
export function reviewPage(env:SoraneAdminEnv,site:Site,proposals:Proposal[],publication:Record<string,unknown>|null,token:string,hidden:()=>string) {
  const route=`/api/sites/${site.id}`, submitted=proposals.filter(proposal=>proposal.state==='submitted');
  const card=(proposal:Proposal)=>{
    const published=publication?.proposal_id===proposal.id, old=proposal.engine_id!==env.EXPECTED_ENGINE;
    const labels={queued:'プレビューを準備中',building:'プレビューを準備中',ready:'確認できます',failed:'原稿の確認が必要です'};
    const ready=proposal.build_status==='ready';
    return `<section class="review-card" id="proposal-${proposal.id}"><div class="review-top"><div><h3>${escape(proposal.source==='artifacts'?'原稿が更新されました':proposal.message)}</h3><p class="review-meta"><span>${date(proposal.created_at)}</span><span>${proposal.source==='artifacts'?'Artifactsのpushで自動作成':'原稿の変更'}</span></p></div><span class="pill ${published?'':proposal.build_status==='failed'?'failed':ready?'':'pending'}">${published?'公開中':labels[proposal.build_status??'queued']}</span></div>${proposal.build_error?`<p class="status-message">${proposal.build_error==='validation_failed'?'原稿のチェックで問題が見つかりました。下の結果を確認して、原稿を修正してください。':'プレビューを作成できませんでした。時間をおいて作り直してください。'}</p>`:''}${validationFeedback(proposal.validation_report)}<div class="review-actions">${can(site.role,'proposal.submit')?`<a class="edit-link" href="/sites/${site.id}?proposal=${proposal.id}">原稿を開く →</a>`:''}${ready?`<button class="secondary" type="button" data-preview="${route}/proposals/${proposal.id}/preview" data-csrf="${token}">${icon('external')}プレビューを見る</button><noscript><form method="post" action="${route}/proposals/${proposal.id}/preview" target="_blank" rel="noopener">${formCsrf(token)}<button>プレビューを見る</button></form></noscript>`:''}${proposal.state==='submitted'&&ready&&!old&&can(site.role,'proposal.approve')?`<form method="post" action="${route}/proposals/${proposal.id}/approve">${hidden()}<input type="hidden" name="commit" value="${proposal.commit_id}"><input type="hidden" name="candidate" value="${proposal.candidate_digest}"><button>${icon('review')}公開する</button></form>`:proposal.state==='submitted'&&(old&&ready||proposal.build_status==='failed')&&can(site.role,'proposal.submit')?`<button type="button" data-rebuild="${route}/editor/rebuild" data-proposal="${proposal.id}" data-revision="${site.revision}" data-csrf="${token}">プレビューを作り直す</button>`:''}</div>${proposal.state==='submitted'&&ready&&old?'<p class="muted">公開するには、現在の環境でプレビューを作り直してください。</p>':''}<p class="status-message" data-status role="status" aria-live="polite"></p><details class="technical"><summary>技術的な詳細</summary><p>コミット：<code>${proposal.commit_id}</code></p>${proposal.candidate_digest?`<p>成果物：<code>${proposal.candidate_digest}</code></p><p>${proposal.file_count}ファイル · ${proposal.total_bytes} bytes</p>`:''}${proposal.build_error?`<p>エラー：<code>${escape(proposal.build_error)}</code></p>`:''}${proposal.draft_digest?`<a href="/sites/${site.id}/proposals/${proposal.id}/draft">原稿の変更内容を見る</a>`:''}</details></section>`;
  };
  const building=proposals.some(proposal=>['queued','building'].includes(proposal.build_status??''));
  return `<div class="heading-row"><div><p class="eyebrow">PUBLISH</p><h1>確認・公開</h1><p>できあがりを確認して、公開しましょう。</p></div>${publication?`<a class="button secondary" href="${escape(env.PUBLIC_ORIGIN)}/${site.id}/" target="_blank" rel="noopener">公開サイトを見る ${icon('external')}</a>`:''}</div><div class="steps"><span><b>1</b>原稿を書く</span><i></i><span><b>2</b>プレビューで確認</span><i></i><span><b>3</b>公開する</span></div><p class="section-label">公開前の変更 <small>${submitted.length}件</small></p>${submitted.length?submitted.map(card).join(''):'<div class="surface empty"><h2>確認待ちの変更はありません</h2><p>記事を編集して保存すると、ここにプレビューが届きます。</p></div>'}${proposals.some(proposal=>proposal.state==='approved')?`<p class="section-label">公開履歴</p>${proposals.filter(proposal=>proposal.state==='approved').map(card).join('')}`:''}${building?`<div data-building="${escape(proposals.map(proposal=>proposal.id+':'+proposal.build_status).join(','))}" data-poll="${route}"></div>`:''}`;
}
export function settingsPage(site:Site,members:{sub:string;role:Role}[],token:string,hidden:()=>string) {
  const route=`/api/sites/${site.id}`;
  return `<div class="heading-row"><div><p class="eyebrow">SETTINGS</p><h1>設定</h1><p>サイトへのアクセスと、接続情報を管理します。</p></div></div><section class="settings-section"><h2>メンバーと権限</h2><p>編集者は原稿を作成・編集でき、公開担当は確認した内容を公開できます。</p><table class="settings-table"><thead><tr><th>メンバー識別子</th><th>役割</th><th></th></tr></thead><tbody>${members.map(member=>`<tr><td><code>${escape(member.sub)}</code></td><td>${roleLabels[member.role]}</td><td><form method="post" action="${route}/members/remove">${hidden()}<input type="hidden" name="sub" value="${escape(member.sub)}"><button class="danger">削除</button></form></td></tr>`).join('')}</tbody></table><h3>メンバーを追加・変更</h3><form class="settings-form" method="post" action="${route}/members">${hidden()}<label>メンバー識別子<input name="sub" required maxlength="255" placeholder="Mikakiの識別子"></label><label>役割<select name="role">${ROLES.map(role=>`<option value="${role}">${roleLabels[role]}</option>`).join('')}</select></label><button>保存</button></form></section><section class="settings-section"><h2>原稿の接続先</h2><p>Artifacts上の原稿を読み込み、変更ごとにプレビューを作成します。</p><p><code>${escape(site.artifact_namespace)}/${escape(site.artifact_repository)}</code></p><details class="technical"><summary>コミットを指定して取り込む</summary><form class="settings-form" method="post" action="${route}/proposals">${hidden()}<label>対象コミット<input name="commit" required pattern="[0-9a-f]{40}" placeholder="40桁のコミットID"></label><label>変更内容<input name="message" required maxlength="1000"></label><button>取り込む</button></form></details></section>`;
}
